// <auto-generated />
namespace pet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2020092102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2020092102));
        
        string IMigrationMetadata.Id
        {
            get { return "202009210904322_2020092102"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
